In [317]:
from ultralytics import YOLO
import os 
import numpy as np 

In [318]:
modelCard = YOLO("../last.pt")

In [319]:
def detectCard(model, path):
    results = model([path])
    print(results)

    for result in results:
        boxes = result.boxes
        for box in boxes:
            print(box)
        masks = result.masks
        keypoints = result.keypoints
        probs = result.probs
        obb = result.obb
        names = result.names
        result.save(filename=path+"OD.jpg")
    
    return boxes, names

In [320]:
def parseBoxes(boxes, names):
    cards = []
    
    if len(boxes) == 0:
        return cards

    cardsDealer = []
    cardsPlayer = []
    
    orig_shapeX, orig_shapeY = boxes[0].orig_shape
    
    print(orig_shapeX)
    print(orig_shapeY)
    
    #It is going to return the type in which it is being considered and the type 
    
    print(names)

    for box in boxes:
        print("Type Card")
        TypeCard = names[int(box.cls.item())]
        print(TypeCard)

        print("Confidence")
        Confidence = round(box.conf.item(),2)
        print(Confidence)
        
        #Card Dictionary
        card = {
            "Conf": Confidence,
            "TypeCard": TypeCard
        }
        
        #From a box 
        #X1Y1
        #       X2Y2
        print("Coordinates")
        #It prints like (X1) 
        print(box.xyxy.numpy())
        Coordinates = box.xyxy.numpy()[0]
        X1 = Coordinates[0]
        Y1 = Coordinates[1] 
        X2 = Coordinates[2]
        Y2 = Coordinates[3]
        
        if Y1 > orig_shapeX / 2 or Y2 > orig_shapeX / 2:
            cardsDealer.append(card)
        else: 
            cardsPlayer.append(card)
        
        print(X1, X2, Y1, Y2)
        
    return cardsDealer, cardsPlayer

In [321]:
boxes, names = detectCard(modelCard, "../screenshots/playing-cards-aces-set_78370-2354.png")


0: 640x640 2 4Ds, 1 4S, 3 ADs, 2 ASs, 126.9ms
Speed: 3.0ms preprocess, 126.9ms inference, 1.6ms postprocess per image at shape (1, 3, 640, 640)
[ultralytics.engine.results.Results object with attributes:

boxes: ultralytics.engine.results.Boxes object
keypoints: None
masks: None
names: {0: '10C', 1: '10D', 2: '10H', 3: '10S', 4: '2C', 5: '2D', 6: '2H', 7: '2S', 8: '3C', 9: '3D', 10: '3H', 11: '3S', 12: '4C', 13: '4D', 14: '4H', 15: '4S', 16: '5C', 17: '5D', 18: '5H', 19: '5S', 20: '6C', 21: '6D', 22: '6H', 23: '6S', 24: '7C', 25: '7D', 26: '7H', 27: '7S', 28: '8C', 29: '8D', 30: '8H', 31: '8S', 32: '9C', 33: '9D', 34: '9H', 35: '9S', 36: 'AC', 37: 'AD', 38: 'AH', 39: 'AS', 40: 'JC', 41: 'JD', 42: 'JH', 43: 'JS', 44: 'KC', 45: 'KD', 46: 'KH', 47: 'KS', 48: 'QC', 49: 'QD', 50: 'QH', 51: 'QS'}
obb: None
orig_img: array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255

In [322]:
cardDealer, cardPlayer = parseBoxes(boxes, names)

338
338
{0: '10C', 1: '10D', 2: '10H', 3: '10S', 4: '2C', 5: '2D', 6: '2H', 7: '2S', 8: '3C', 9: '3D', 10: '3H', 11: '3S', 12: '4C', 13: '4D', 14: '4H', 15: '4S', 16: '5C', 17: '5D', 18: '5H', 19: '5S', 20: '6C', 21: '6D', 22: '6H', 23: '6S', 24: '7C', 25: '7D', 26: '7H', 27: '7S', 28: '8C', 29: '8D', 30: '8H', 31: '8S', 32: '9C', 33: '9D', 34: '9H', 35: '9S', 36: 'AC', 37: 'AD', 38: 'AH', 39: 'AS', 40: 'JC', 41: 'JD', 42: 'JH', 43: 'JS', 44: 'KC', 45: 'KD', 46: 'KH', 47: 'KS', 48: 'QC', 49: 'QD', 50: 'QH', 51: 'QS'}
Type Card
AD
Confidence
0.78
Coordinates
[[     125.84      118.61      143.38      152.21]]
125.83893 143.37526 118.608894 152.20943
Type Card
4D
Confidence
0.78
Coordinates
[[      52.34      15.373      71.712      49.938]]
52.340042 71.71181 15.373256 49.938168
Type Card
AD
Confidence
0.66
Coordinates
[[     264.01      116.14       281.5      152.26]]
264.01465 281.50467 116.1352 152.26399
Type Card
AS
Confidence
0.6
Coordinates
[[     52.152      180.62      70.668  

In [323]:
def parseCards(setCards):
    cardsParsed = []
    
    for card in setCards:
        toParse = True
        
        if len(cardsParsed) == 0:
            toParse = True
                
        else:
            for cardP in cardsParsed:
                if cardP["TypeCard"] == card["TypeCard"]:
                    toParse = False 
                    if card["Conf"] > cardP["Conf"]:
                        cardP["Conf"] = card["Conf"]
            
        if toParse:    
            cardsParsed.append(card) 
           
    print(cardsParsed)
    return cardsParsed

In [324]:
print(cardDealer)
print(cardPlayer)

[{'Conf': 0.6, 'TypeCard': 'AS'}, {'Conf': 0.53, 'TypeCard': 'AS'}, {'Conf': 0.51, 'TypeCard': '4S'}]
[{'Conf': 0.78, 'TypeCard': 'AD'}, {'Conf': 0.78, 'TypeCard': '4D'}, {'Conf': 0.66, 'TypeCard': 'AD'}, {'Conf': 0.57, 'TypeCard': 'AD'}, {'Conf': 0.38, 'TypeCard': '4D'}]


In [325]:
dealerParsed = parseCards(cardDealer) 
playerParsed = parseCards(cardPlayer)

[{'Conf': 0.6, 'TypeCard': 'AS'}, {'Conf': 0.51, 'TypeCard': '4S'}]
[{'Conf': 0.78, 'TypeCard': 'AD'}, {'Conf': 0.78, 'TypeCard': '4D'}]


In [326]:
def translateArray(cards):
    array = np.zeros(13)
    
    for card in cards:
        print(card["TypeCard"])
        cat = categoryCard(card["TypeCard"])
        value = valueCard(card["TypeCard"], cat)
        array[value - 1] = array[value - 1] + 1

    print(array)
    return array


typesCards = ["S", "D", "C", "H"]


def categoryCard(card):
    if typesCards[0] in card:
        return 0
    elif typesCards[1] in card:
        return 1
    elif typesCards[2] in card:
        return 2
    elif typesCards[3] in card:
        return 3


def valueCard(card, cat):
    value = card[0].split(typesCards[cat])[0]
    if value == "A":
        return 1
    elif value == "J":
        return 11
    elif value == "Q":
        return 12
    elif value == "K":
        return 13
    else:
        return int(value)


def countCards(arrayCards):
    arrayTMP = arrayCards
    count = 0
    ace = False
    for index in range(13):
        if arrayTMP[index] >= 1:
            if index == 0:
                ace = True
                if arrayTMP[index] == 2:
                    count = 21
                    ace = False
                else:
                    count = arrayTMP[index] * 1 + count
            elif index == 10:
                count = count + arrayTMP[index] * 10
            elif index == 11:
                count = count + arrayTMP[index] * 10
            elif index == 12:
                count = count + arrayTMP[index] * 10
            else:
                count = count + arrayTMP[index] * (index + 1)

    if ace and count < 11:
        count = count + 11

    return count-1

In [327]:
arrayDealer = translateArray(dealerParsed)
arrayPlayer = translateArray(playerParsed)

AS
4S
[          1           0           0           1           0           0           0           0           0           0           0           0           0]
AD
4D
[          1           0           0           1           0           0           0           0           0           0           0           0           0]


In [328]:
print(countCards(arrayDealer))
print(countCards(arrayPlayer))

15.0
15.0
